// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2ZtJR0PCHVdBheqgCcPKLfhjBnrzZ-pQ',
    appId: '1:792919281292:web:f8bc7bd73a757bf91635a9',
    messagingSenderId: '792919281292',
    projectId: 'perpus-ku',
    authDomain: 'perpus-ku.firebaseapp.com',
    storageBucket: 'perpus-ku.appspot.com',
    measurementId: 'G-Z9RPY9TVJP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw5S38jB_-O36hvZT_cawoJK_GqrVfu6I',
    appId: '1:792919281292:android:57be5723cd6a18ef1635a9',
    messagingSenderId: '792919281292',
    projectId: 'perpus-ku',
    storageBucket: 'perpus-ku.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgksgGuvWl6pqHaEGDSaHKQirxxJIhSfY',
    appId: '1:792919281292:ios:515f3f538eb2533e1635a9',
    messagingSenderId: '792919281292',
    projectId: 'perpus-ku',
    storageBucket: 'perpus-ku.appspot.com',
    iosBundleId: 'com.example.perpusDigital',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgksgGuvWl6pqHaEGDSaHKQirxxJIhSfY',
    appId: '1:792919281292:ios:515f3f538eb2533e1635a9',
    messagingSenderId: '792919281292',
    projectId: 'perpus-ku',
    storageBucket: 'perpus-ku.appspot.com',
    iosBundleId: 'com.example.perpusDigital',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2ZtJR0PCHVdBheqgCcPKLfhjBnrzZ-pQ',
    appId: '1:792919281292:web:0e7d2fa0c839bf781635a9',
    messagingSenderId: '792919281292',
    projectId: 'perpus-ku',
    authDomain: 'perpus-ku.firebaseapp.com',
    storageBucket: 'perpus-ku.appspot.com',
    measurementId: 'G-DZ0ZNFEG4B',
  );
}
